"""Generated by `top100_membership.py` -- do not hand-edit.

The point-in-time TOP 100 US stocks, ranked by trailing 252-day median dollar volume among
S&P 500 members on each rebalance date, annually, with a 120-rank buffer on
incumbents.

`TOP100_ALL` is the union of every name that ever held a slot and it is what gets
*fetched*. Which names are actually *held on a given date* is decided per-bar by
`top100_membership.load()` + `portfolio_wf.membership_mask`, never by this list -- holding
all 216 of them at once would be a top-216 study, not a top-100 one.

`TOP100_CURRENT` is the 100 names in the universe as of the last rebalance.

Dollar volume is a PROXY for size: this repo has no historical shares-outstanding series,
so a true market-cap ranking is not computable here. It favours high-turnover names and
penalises quiet giants; see the module docstring of `top100_membership.py` for the full
statement of what that costs.

Rebuild with::

    python top100_membership.py
"""

# Every name that ever held a top-100 slot, 216 in total.
TOP100_ALL = [
    "A", "AA", "AAL", "AAPL", "ABBV", "ABNB", "ABT", "ACN",
    "ADBE", "ADI", "ADP", "AES", "AIG", "AKAM", "ALL", "AMAT",
    "AMD", "AMGN", "AMZN", "ANET", "ANF", "APA", "APC", "APP",
    "ATI", "AVGO", "AXP", "AZO", "BA", "BAC", "BAX", "BBY",
    "BIIB", "BKNG", "BMY", "BNY", "BRK.B", "BSX", "C", "CAH",
    "CAT", "CCL", "CF", "CHTR", "CI", "CIEN", "CL", "CLF",
    "CLX", "CMCSA", "CME", "CMG", "CNX", "COF", "COIN", "COP",
    "COST", "CPRI", "CRM", "CRWD", "CSCO", "CSX", "CVNA", "CVS",
    "CVX", "DAL", "DD", "DE", "DELL", "DG", "DHR", "DIS",
    "DVN", "EA", "EBAY", "ELV", "EMR", "ENPH", "EOG", "F",
    "FCX", "FDX", "FFIV", "FIS", "FISV", "FITB", "FLR", "FSLR",
    "GD", "GE", "GEN", "GEV", "GILD", "GLW", "GOOG", "GOOGL",
    "GPS", "GS", "GT", "HAL", "HD", "HIG", "HOOD", "HPQ",
    "IBM", "ICE", "INTC", "INTU", "IP", "ISRG", "JBL", "JCI",
    "JNJ", "JPM", "KBH", "KMB", "KMI", "KO", "KR", "KSS",
    "LEN", "LIN", "LLY", "LMT", "LOW", "LRCX", "LUV", "M",
    "MA", "MAT", "MCD", "MCHP", "MCK", "MDLZ", "MDT", "MET",
    "META", "MMM", "MO", "MOS", "MPC", "MRK", "MRNA", "MRSH",
    "MS", "MSFT", "MSI", "MU", "NBR", "NCLH", "NEE", "NEM",
    "NFLX", "NKE", "NOC", "NOV", "NOW", "NTAP", "NUE", "NVDA",
    "OMC", "ORCL", "OXY", "PANW", "PAYX", "PEP", "PFE", "PG",
    "PHM", "PLTR", "PM", "PNC", "PSKY", "PYPL", "QCOM", "RCL",
    "REGN", "RIG", "RTX", "SBUX", "SCHW", "SLB", "SMCI", "SPGI",
    "STT", "T", "TER", "TGT", "THC", "TJX", "TMO", "TMUS",
    "TRV", "TSLA", "TXN", "UAL", "UBER", "UNH", "UNP", "UPS",
    "USB", "V", "VLO", "VRSN", "VRTX", "VTRS", "VZ", "WAT",
    "WDC", "WFC", "WM", "WMT", "WYNN", "XOM", "YUM", "ZBH",
]

# The 100 names in the universe at the most recent rebalance.
TOP100_CURRENT = [
    "AAPL", "ABBV", "ABNB", "ABT", "ACN", "ADBE", "AMAT", "AMD",
    "AMGN", "AMZN", "ANET", "APP", "AVGO", "AXP", "BA", "BAC",
    "BKNG", "BMY", "BRK.B", "C", "CAT", "CMCSA", "CMG", "COIN",
    "COP", "COST", "CRM", "CRWD", "CSCO", "CVNA", "CVX", "DE",
    "DELL", "DHR", "DIS", "ELV", "F", "FCX", "GE", "GEV",
    "GILD", "GOOG", "GOOGL", "GS", "HD", "HOOD", "IBM", "INTC",
    "INTU", "ISRG", "JNJ", "JPM", "KO", "LIN", "LLY", "LMT",
    "LOW", "LRCX", "MA", "MCD", "MDT", "META", "MRK", "MS",
    "MSFT", "MU", "NEE", "NFLX", "NKE", "NOW", "NVDA", "ORCL",
    "PANW", "PEP", "PFE", "PG", "PLTR", "PYPL", "QCOM", "REGN",
    "RTX", "SBUX", "SCHW", "SMCI", "SPGI", "T", "TGT", "TMO",
    "TMUS", "TSLA", "TXN", "UBER", "UNH", "UNP", "V", "VRTX",
    "VZ", "WFC", "WMT", "XOM",
]

assert len(TOP100_ALL) == 216, "regenerate: membership changed"
assert len(TOP100_CURRENT) == 100, "regenerate: membership changed"
