"""GENERATED by `futures_screen.py --write`. Do not edit.

The CME roots that survived the liquidity, history, price-grid and correlation
gates. `config.CME_POOL` is what was ranked; this is what is traded.
"""

CME_SCREENED = [
    "ES.v.0",     # E-mini S&P 500, $579.7B/day
    "ZN.v.0",     # 10-Year T-Note, $131.0B/day
    "GC.v.0",     # Gold, $70.0B/day
    "ZT.v.0",     # 2-Year T-Note, $56.3B/day
    "6E.v.0",     # Euro FX, $26.9B/day
    "CL.v.0",     # WTI Crude Oil, $22.0B/day
    "SI.v.0",     # Silver, $15.6B/day
    "6J.v.0",     # Japanese Yen, $9.1B/day
    "HG.v.0",     # Copper, $8.2B/day
    "6B.v.0",     # British Pound, $7.7B/day
    "6A.v.0",     # Australian Dollar, $6.2B/day
    "HO.v.0",     # NY Harbor ULSD, $5.2B/day
    "6C.v.0",     # Canadian Dollar, $4.8B/day
    "ZS.v.0",     # Soybeans, $4.7B/day
    "6S.v.0",     # Swiss Franc, $3.6B/day
    "RB.v.0",     # RBOB Gasoline, $3.5B/day
    "ZC.v.0",     # Corn, $2.8B/day
    "NG.v.0",     # Henry Hub Natural Gas, $2.6B/day
    "NKD.v.0",    # Nikkei 225 (USD), $2.5B/day
    "ZL.v.0",     # Soybean Oil, $1.7B/day
    "ZW.v.0",     # Chicago SRW Wheat, $1.5B/day
    "LE.v.0",     # Live Cattle, $1.5B/day
    "6N.v.0",     # New Zealand Dollar, $1.2B/day
    "6M.v.0",     # Mexican Peso, $1.2B/day
    "PL.v.0",     # Platinum, $1.1B/day
    "ZM.v.0",     # Soybean Meal, $1.1B/day
]
