"""Generated by `sp500_membership.py --emit` — do not hand-edit.

The S&P 500 universe, point-in-time. `SP500_CURRENT` is today's index; `SP500_DEPARTED`
is every name that left it during the changelog's dense era (2007-) and that Twelve Data
will still price. `SP500_ALL` is the union, and it is what gets *fetched* — which names
are actually *tradeable on a given date* is decided per-bar by
`sp500_membership.membership_on`, never by this list.

Fetching the union rather than today's index is the whole point: 248 of these names
are in the file precisely because they are no longer in the index, and a backtest that
only ever saw survivors is the bias this repo has carried since study one.

What is still missing, and it is not nothing. 107 departures do not price at all —
Twelve Data does not serve delisted equities — and a further 13 pass the
`/earliest_timestamp` probe but return no bars: AKS, AVP, CXO, DNB, DNR, ETFC, FNM, GAS,
MEE, RAD, RTN, SCG, WIN. That second list is the more damaging one, because it is not
random: **RAD** (Chapter 11, 2023), **WIN** (Chapter 11, 2019), **DNR** (Chapter 11,
2020) and **FNM** (delisted from the NYSE after conservatorship) are exactly the
outcomes a mean-reversion rule needs to be tested against. Wikipedia's free-text reason
field labels only one removal a bankruptcy; the ticker probe says otherwise, so trust the
probe. Roughly 120 of 858 names cannot be held, they skew toward failures, and every
survivorship claim made on this universe should say so.

Rebuild with::

    python sp500_membership.py --probe --emit
"""

# Today's index, 503 lines including multiple share classes (GOOG/GOOGL, FOX/FOXA).
SP500_CURRENT = [
    "A", "AAPL", "ABBV", "ABNB", "ABT", "ACGL", "ACN", "ADBE",
    "ADI", "ADM", "ADP", "ADSK", "AEE", "AEP", "AES", "AFL",
    "AIG", "AIZ", "AJG", "AKAM", "ALB", "ALGN", "ALL", "ALLE",
    "AMAT", "AMCR", "AMD", "AME", "AMGN", "AMP", "AMT", "AMZN",
    "ANET", "AON", "AOS", "APA", "APD", "APH", "APO", "APP",
    "APTV", "ARE", "ARES", "ATO", "AVB", "AVGO", "AVY", "AWK",
    "AXON", "AXP", "AZO", "BA", "BAC", "BALL", "BAX", "BBY",
    "BDX", "BEN", "BF.B", "BG", "BIIB", "BKNG", "BKR", "BLDR",
    "BLK", "BMY", "BNY", "BR", "BRK.B", "BRO", "BSX", "BX",
    "BXP", "C", "CAH", "CARR", "CASY", "CAT", "CB", "CBOE",
    "CBRE", "CCI", "CCL", "CDNS", "CDW", "CEG", "CF", "CFG",
    "CHD", "CHRW", "CHTR", "CI", "CIEN", "CINF", "CL", "CLX",
    "CMCSA", "CME", "CMG", "CMI", "CMS", "CNC", "CNP", "COF",
    "COHR", "COIN", "COO", "COP", "COR", "COST", "CPAY", "CPRT",
    "CPT", "CRH", "CRL", "CRM", "CRWD", "CSCO", "CSGP", "CSX",
    "CTAS", "CTSH", "CTVA", "CVNA", "CVS", "CVX", "D", "DAL",
    "DASH", "DD", "DDOG", "DE", "DECK", "DELL", "DG", "DGX",
    "DHI", "DHR", "DIS", "DLR", "DLTR", "DOC", "DOV", "DOW",
    "DPZ", "DRI", "DTE", "DUK", "DVA", "DVN", "DXCM", "EBAY",
    "ECHO", "ECL", "ED", "EFX", "EG", "EIX", "EL", "ELV",
    "EME", "EMR", "EOG", "EQIX", "EQR", "EQT", "ERIE", "ES",
    "ESS", "ETN", "ETR", "EVRG", "EW", "EXC", "EXE", "EXPD",
    "EXPE", "EXR", "F", "FANG", "FAST", "FCX", "FDS", "FDX",
    "FDXF", "FE", "FERG", "FFIV", "FICO", "FIS", "FISV", "FITB",
    "FIX", "FLEX", "FOX", "FOXA", "FRT", "FSLR", "FTNT", "FTV",
    "GD", "GDDY", "GE", "GEHC", "GEN", "GEV", "GILD", "GIS",
    "GL", "GLW", "GM", "GNRC", "GOOG", "GOOGL", "GPC", "GPN",
    "GRMN", "GS", "GWW", "HAL", "HAS", "HBAN", "HCA", "HD",
    "HIG", "HII", "HLT", "HON", "HONA", "HOOD", "HPE", "HPQ",
    "HRL", "HSIC", "HST", "HSY", "HUBB", "HUM", "HWM", "IBKR",
    "IBM", "ICE", "IDXX", "IEX", "IFF", "INCY", "INTC", "INTU",
    "INVH", "IP", "IQV", "IR", "IRM", "ISRG", "IT", "ITW",
    "IVZ", "J", "JBHT", "JBL", "JCI", "JKHY", "JNJ", "JPM",
    "KDP", "KEY", "KEYS", "KHC", "KIM", "KKR", "KLAC", "KMB",
    "KMI", "KO", "KR", "KVUE", "L", "LDOS", "LEN", "LH",
    "LHX", "LII", "LIN", "LITE", "LLY", "LMT", "LNT", "LOW",
    "LRCX", "LULU", "LUV", "LVS", "LYB", "LYV", "MA", "MAA",
    "MAR", "MAS", "MCD", "MCHP", "MCK", "MCO", "MDLZ", "MDT",
    "MET", "META", "MGM", "MKC", "MLM", "MMM", "MNST", "MO",
    "MOS", "MPC", "MPWR", "MRK", "MRNA", "MRSH", "MRVL", "MS",
    "MSCI", "MSFT", "MSI", "MTB", "MTD", "MU", "NCLH", "NDAQ",
    "NDSN", "NEE", "NEM", "NFLX", "NI", "NKE", "NOC", "NOW",
    "NRG", "NSC", "NTAP", "NTRS", "NUE", "NVDA", "NVR", "NWS",
    "NWSA", "NXPI", "O", "ODFL", "OKE", "OMC", "ON", "ORCL",
    "ORLY", "OTIS", "OXY", "PANW", "PAYX", "PCAR", "PCG", "PEG",
    "PEP", "PFE", "PFG", "PG", "PGR", "PH", "PHM", "PKG",
    "PLD", "PLTR", "PM", "PNC", "PNR", "PNW", "PODD", "PPG",
    "PPL", "PRU", "PSA", "PSKY", "PSX", "PTC", "PWR", "PYPL",
    "Q", "QCOM", "RCL", "REG", "REGN", "RF", "RJF", "RL",
    "RMD", "ROK", "ROL", "ROP", "ROST", "RSG", "RTX", "RVTY",
    "SBAC", "SBUX", "SCHW", "SHW", "SJM", "SLB", "SMCI", "SNA",
    "SNDK", "SNPS", "SO", "SOLV", "SPG", "SPGI", "SRE", "STE",
    "STLD", "STT", "STX", "STZ", "SW", "SWK", "SWKS", "SYF",
    "SYK", "SYY", "T", "TAP", "TDG", "TDY", "TECH", "TEL",
    "TER", "TFC", "TGT", "TJX", "TKO", "TMO", "TMUS", "TPL",
    "TPR", "TRGP", "TRMB", "TROW", "TRV", "TSCO", "TSLA", "TSN",
    "TT", "TTD", "TTWO", "TXN", "TXT", "TYL", "UAL", "UBER",
    "UDR", "UHS", "ULTA", "UNH", "UNP", "UPS", "URI", "USB",
    "V", "VEEV", "VICI", "VLO", "VLTO", "VMC", "VRSK", "VRSN",
    "VRT", "VRTX", "VST", "VTR", "VTRS", "VZ", "WAB", "WAT",
    "WBD", "WDAY", "WDC", "WEC", "WELL", "WFC", "WM", "WMB",
    "WMT", "WRB", "WSM", "WST", "WTW", "WY", "WYNN", "XEL",
    "XOM", "XYL", "XYZ", "YUM", "ZBH", "ZBRA", "ZTS",
]

# Left the index 2007-2026 and still priceable. Held only for the dates they were members.
SP500_DEPARTED = [
    "AA", "AAL", "AAP", "ABK", "ACE", "ADCT", "ADS", "ADT",
    "AET", "AGN", "AIV", "AKS", "ALK", "ALTR", "AMG", "AMTM",
    "AN", "ANF", "APC", "ARG", "ATI", "AV", "AVP", "AYE",
    "AYI", "BBBY", "BBWI", "BC", "BEAM", "BHF", "BHI", "BIG",
    "BIO", "BMS", "BTU", "BWA", "CA", "CAG", "CAM", "CBE",
    "CCE", "CCK", "CDAY", "CE", "CFC", "CHK", "CLF", "CMA",
    "CNX", "COL", "COTY", "COV", "CPB", "CPRI", "CPWR", "CSC",
    "CSRA", "CTRA", "CVC", "CVG", "CVH", "CXO", "CZR", "DF",
    "DFS", "DISH", "DNB", "DNR", "DV", "DXC", "DYN", "EA",
    "EMC", "EMN", "ENPH", "EP", "EPAM", "ETFC", "ETSY", "FBHS",
    "FDC", "FDO", "FHN", "FII", "FL", "FLR", "FLS", "FLT",
    "FMC", "FNM", "FOSL", "FRC", "FRE", "FRX", "FTI", "GAS",
    "GENZ", "GGP", "GHC", "GME", "GNW", "GPS", "GR", "GRA",
    "GRN", "GT", "HAR", "HFC", "HOG", "HOT", "HP", "HRB",
    "HSP", "IGT", "ILMN", "INFO", "IPGP", "ITT", "JEF", "JNPR",
    "JOY", "K", "KBH", "KG", "KMX", "KSE", "KSS", "LEG",
    "LEH", "LIFE", "LKQ", "LLL", "LNC", "LSI", "LUMN", "LW",
    "M", "MAC", "MAT", "MBC", "MBI", "MDP", "MEE", "MFE",
    "MHK", "MI", "MIL", "MKTX", "MMI", "MNK", "MOH", "MON",
    "MRO", "MTCH", "MUR", "NAVI", "NBL", "NBR", "NE", "NFX",
    "NKTR", "NOV", "NWL", "NYT", "OGN", "OI", "PAYC", "PBI",
    "PCL", "PCS", "PENN", "PGN", "PLL", "POM", "POOL", "PRGO",
    "PVH", "QRVO", "R", "RAD", "RDC", "RE", "RHI", "RHT",
    "RIG", "RRC", "RSH", "RTN", "RX", "S", "SAI", "SBL",
    "SBNY", "SCG", "SE", "SEDG", "SEE", "SGP", "SHLD", "SIG",
    "SII", "SLE", "SLG", "SLM", "SLR", "SOLS", "SPLS", "STI",
    "STJ", "STR", "SUN", "SWN", "TDC", "TE", "TEG", "TFX",
    "TGNA", "THC", "TIE", "TIF", "TMC", "TRB", "TRIP", "TSG",
    "TSS", "TWC", "UA", "UAA", "UNM", "URBN", "USL", "VFC",
    "VNO", "VNT", "WB", "WFR", "WHR", "WIN", "WLTW", "WU",
    "WYN", "X", "XEC", "XL", "XRAY", "XRX", "YHOO", "ZION",
]

SP500_ALL = sorted(set(SP500_CURRENT) | set(SP500_DEPARTED))
assert len(SP500_ALL) == 751, "regenerate: membership changed"
