"""GENERATED by `futures_screen.py --write`. Do not edit.

The CME roots that survived the liquidity, history, price-grid and correlation
gates. `config.CME_POOL` is what was ranked; this is what is traded.
"""

CME_SCREENED = [
    "ES.v.0",     # E-mini S&P 500, $579.7B/day
    "GC.v.0",     # Gold, $70.0B/day
    "CL.v.0",     # WTI Crude Oil, $22.0B/day
    "SI.v.0",     # Silver, $15.6B/day
    "HG.v.0",     # Copper, $8.2B/day
    "HO.v.0",     # NY Harbor ULSD, $5.2B/day
    "ZS.v.0",     # Soybeans, $4.7B/day
    "RB.v.0",     # RBOB Gasoline, $3.5B/day
    "ZC.v.0",     # Corn, $2.8B/day
    "NG.v.0",     # Henry Hub Natural Gas, $2.6B/day
    "NKD.v.0",    # Nikkei 225 (USD), $2.5B/day
    "ZL.v.0",     # Soybean Oil, $1.7B/day
    "ZW.v.0",     # Chicago SRW Wheat, $1.5B/day
    "LE.v.0",     # Live Cattle, $1.5B/day
    "PL.v.0",     # Platinum, $1.1B/day
    "ZM.v.0",     # Soybean Meal, $1.1B/day
]
