"""Build the dashboard. One payload, two emitters.

    python build_dashboard.py --serve          # -> web/data.js + web/curves/*.json
    python build_dashboard.py --dist           # -> dist/dashboard.html (self-contained)
    python build_dashboard.py --serve --dist   # both, from one pass over the results
    python build_dashboard.py --serve --offline    # skip the live price snapshot

There used to be two independent builders here. `build_web_data.py` fed the served SPA
from the walk-forward leaderboards; `build_dashboard.py` + `build_dashboard_data.py` fed
a separate single-file board from a different subset of the same CSVs, with its own
hand-written CSS and JS. They drifted -- at the time of the merge the single-file board
was a day stale and did not show paper trading at all, which is the thing the dashboard
exists to watch. Now `payload.py` builds one document and this file emits it two ways.

**--serve** writes `web/data.js` and mirrors the curve JSONs into `web/curves/`. The SPA
reads `data.js` at load and fetches the rest on demand, including `live.json`, which the
paper desk republishes every couple of seconds while it runs.

**--dist** inlines the stylesheet, the application and the payload into a single file that
works from `file://` with no server. The SPA is not modified to do this: a small shim
installed ahead of `app.js` answers its four relative `fetch()` calls out of an embedded
map and stubs the WebSocket, so the same application code renders a frozen snapshot. That
keeps one implementation of every view instead of two.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from datetime import datetime, timezone

import dash_config
import payload as payload_mod

WEB = dash_config.WEB
DIST = dash_config.DIST

# Assets the single-file build folds in. `demo_data.js` is deliberately absent: it is the
# layout fixture and must never ship.
DIST_ASSETS = ("app.css", "app.js")


def _take_files(payload: dict) -> tuple[dict, dict[str, str]]:
    """Split `payload["_files"]` off the document, returning `(payload, files)`.

    `payload.build` uses `_files` as a side channel for generated files that must reach
    both outputs -- `robust.json`, the leaderboard's compact `curves/board_*.json` -- and
    it must never be serialised into `window.DASH`: it is the file contents a second time,
    inlined, which is precisely what moving them out was for. So every emitter takes it off
    before it dumps.

    It returns a shallow COPY rather than mutating, because `--serve --dist` hands the same
    document to both emitters and a destructive pop in the first would leave the second
    with nothing to embed. The copy is one dict of top-level keys, which costs nothing
    beside the JSON dump the caller is about to do.
    """
    files = payload.get("_files") or {}
    return {k: v for k, v in payload.items() if k != "_files"}, files


def emit_serve(payload: dict) -> None:
    # Strip the side channel BEFORE the dump, then publish its contents as real files under
    # `web/`. The keys are already the relative URLs `app.js` fetches, so they are the paths
    # verbatim; parents are created because those URLs have a directory in them
    # (`curves/board_stocks_1d.json`) and a first build has no `web/curves/` yet.
    payload, files = _take_files(payload)
    for name, blob in sorted(files.items()):
        dst = WEB / name
        dst.parent.mkdir(parents=True, exist_ok=True)
        dst.write_text(blob, encoding="utf-8")
    if files:
        total = sum(len(b.encode("utf-8")) for b in files.values())
        print(f"  wrote {len(files)} inline file(s) under web/ ({total / 1e3:.0f} kB): "
              + ", ".join(sorted(files)[:3])
              + (f", +{len(files) - 3} more" if len(files) > 3 else ""))
    out = WEB / "data.js"
    out.write_text("/* GENERATED by build_dashboard.py --serve - do not edit. */\n"
                   "window.DEMO = false;\nwindow.DASH = "
                   + json.dumps(payload, separators=(",", ":")) + ";\n",
                   encoding="utf-8")
    print(f"  wrote {out.relative_to(dash_config.REPO)} "
          f"({out.stat().st_size / 1e3:.0f} kB)")
    stamp_cache_busters()


def stamp_cache_busters() -> None:
    """Point `index.html`'s `?v=` query strings at the CONTENT of the files they load.

    `index.html` is hand-written and its two script tags carried hand-bumped version
    numbers. That is a rebuild step nobody remembers, and forgetting it is silent in the
    worst way: the build succeeds, the files on disk are correct, and a returning browser
    keeps running the JavaScript and the payload it cached last week. It cost a real
    afternoon — a chart was read as current, questioned as a bug, and was neither.

    So the stamp is derived rather than typed: eight hex characters of the file's SHA-256.
    Same bytes, same URL, browser cache still valid; one byte different, new URL, fetched.
    `index.html` stays a source file — this rewrites nothing but the digits.

    Only the served site needs it. `dist/dashboard.html` inlines everything and has no URL
    to bust.
    """
    idx = WEB / "index.html"
    if not idx.exists():
        return
    html = original = idx.read_text(encoding="utf-8")
    for name in ("data.js", "app.js", "app.css"):
        f = WEB / name
        if not f.exists():
            continue
        digest = hashlib.sha256(f.read_bytes()).hexdigest()[:8]
        html = re.sub(rf'({re.escape(name)})\?v=[^"\']*', rf'\1?v={digest}', html)
    if html != original:
        idx.write_text(html, encoding="utf-8")
        print("  stamped index.html cache-busters")


def _embedded_files(payload: dict, with_curves: bool) -> dict[str, str]:
    """The relative URLs `app.js` fetches, mapped to their contents.

    Keys match exactly what the application asks for -- `paper_curves.json`, `live.json`
    and each `curves/<key>_<tf>.json` -- so the shim can answer without app.js knowing.
    A file that is simply absent (no desk has run yet, say) is left out, and the
    application's existing catch handles it the same way it would a 404.
    """
    files: dict[str, str] = {}
    names = ["live.json", "paper_curves.json"]
    if with_curves:
        # `board_*` is deliberately NOT read off disk. Those entries are delivered through
        # the payload's `_files` side channel and merged in by `emit_dist`, so one key has
        # exactly one source of bytes. Walking them here as well would embed whatever the
        # last `--serve` left in `web/curves/` -- which for a `--dist`-only build could be
        # any age at all, and would silently disagree with the leaderboard rows in the same
        # file. The detail-page curves still come off disk because that is the only place
        # `copy_curves` puts them.
        names += [e["file"] for k, e in payload.get("curves", {}).items()
                  if not k.startswith("board_")]
    for name in names:
        p = WEB / name
        if p.exists():
            files[name] = p.read_text(encoding="utf-8")
    return files


SHIM = """
/* Single-file build. `app.js` is unmodified; these two stubs are what let it run with no
   server behind it. Every fetch it makes is same-origin and relative, so answering them
   from an embedded map is enough -- and anything not embedded falls through to a 404,
   which the application already treats as "no data" rather than an error. */
(function () {
  var FILES = window.__EMBEDDED__ || {};
  window.fetch = function (url) {
    var key = String(url).split("?")[0].replace(/^\\.\\//, "");
    if (Object.prototype.hasOwnProperty.call(FILES, key)) {
      return Promise.resolve({ ok: true, status: 200,
        json: function () { return Promise.resolve(JSON.parse(FILES[key])); },
        text: function () { return Promise.resolve(FILES[key]); } });
    }
    return Promise.resolve({ ok: false, status: 404, statusText: "not in this build",
      json: function () { return Promise.reject(new Error("404")); },
      text: function () { return Promise.resolve(""); } });
  };
  /* No socket to open from file://, and the real one would retry with backoff forever. */
  window.WebSocket = function () {
    return { close: function () {}, send: function () {}, readyState: 3 };
  };
})();
"""


def emit_dist(payload: dict, with_curves: bool) -> None:
    # Same strip as `emit_serve`, and for the same reason -- the embedded map already holds
    # these bytes, so leaving `_files` in the payload would ship every one of them twice.
    payload, inline = _take_files(payload)
    DIST.mkdir(parents=True, exist_ok=True)
    css = (WEB / "app.css").read_text(encoding="utf-8")
    app = (WEB / "app.js").read_text(encoding="utf-8")
    shell = (WEB / "index.html").read_text(encoding="utf-8")
    files = _embedded_files(payload, with_curves)
    # The side channel's keys ARE the relative URLs the shim answers, so they slot straight
    # in, and they win over anything read off disk. `--no-curves` does not drop them: it
    # exists to leave out the ~4 MB of per-detail-page series, and these are two orders of
    # magnitude smaller and back the leaderboard's own chart -- the one picture the reader
    # sees without navigating anywhere.
    files.update(inline)

    # Take the body out of the served shell rather than restating the markup, so the two
    # builds cannot drift apart in structure the way the old pair did.
    body = shell[shell.index("<body>") + len("<body>"):shell.index("</body>")]
    body = body[:body.index("<script")]
    stamp = payload["generated_at"]

    doc = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>Stockhunt &middot; Truong's Dashboard</title>
<style>
{css}
</style>
</head>
<body>
{body}
<script>
window.DEMO = false;
window.DASH = {json.dumps(payload, separators=(",", ":"))};
window.__EMBEDDED__ = {json.dumps(files, separators=(",", ":"))};
window.__SNAPSHOT__ = true;
</script>
<script>{SHIM}</script>
<script>
  document.getElementById("m-feed").textContent = DASH.feed.source + " (snapshot)";
  document.getElementById("m-time").textContent = DASH.generated_at;
</script>
<script>
{app}
</script>
</body>
</html>
"""
    out = DIST / "dashboard.html"
    out.write_text(doc, encoding="utf-8")
    mb = out.stat().st_size / 1e6
    print(f"  wrote {out.relative_to(dash_config.REPO)} ({mb:.1f} MB, "
          f"{len(files)} embedded file(s), curves {'in' if with_curves else 'out'})")
    print(f"        snapshot of {stamp} - it cannot refresh itself")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--serve", action="store_true",
                    help="write web/data.js and web/curves/ for the served site")
    ap.add_argument("--dist", action="store_true",
                    help="write dist/dashboard.html, self-contained")
    ap.add_argument("--no-curves", action="store_true",
                    help="--dist only: leave the backtest curve JSONs out (~4 MB smaller; "
                         "rule detail pages then show no chart)")
    ap.add_argument("--offline", action="store_true",
                    help="skip the live price snapshot, the only network call here")
    args = ap.parse_args()

    if not (args.serve or args.dist):
        ap.error("nothing to do: pass --serve, --dist, or both")

    print(f"building dashboard payload  ({datetime.now(timezone.utc):%Y-%m-%d %H:%M UTC})")
    # --serve mirrors the curve files into web/; --dist alone must not touch the served
    # site, so it takes the index without the copies.
    data = payload_mod.build(copy_curve_files=args.serve, offline=args.offline)
    payload_mod.report(data)

    if args.serve:
        emit_serve(data)
    if args.dist:
        emit_dist(data, with_curves=not args.no_curves)


if __name__ == "__main__":
    main()
