"""Build the dashboard. One payload, two emitters.

    python build_dashboard.py --serve          # -> web/data.js + web/curves/*.json
    python build_dashboard.py --dist           # -> dist/dashboard.html (self-contained)
    python build_dashboard.py --serve --dist   # both, from one pass over the results
    python build_dashboard.py --serve --offline    # skip the live price snapshot

There used to be two independent builders here. `build_web_data.py` fed the served SPA
from the walk-forward leaderboards; `build_dashboard.py` + `build_dashboard_data.py` fed
a separate single-file board from a different subset of the same CSVs, with its own
hand-written CSS and JS. They drifted -- at the time of the merge the single-file board
was a day stale and did not show paper trading at all, which is the thing the dashboard
exists to watch. Now `payload.py` builds one document and this file emits it two ways.

**--serve** writes `web/data.js` and mirrors the curve JSONs into `web/curves/`. The SPA
reads `data.js` at load and fetches the rest on demand, including `live.json`, which the
paper desk republishes every couple of seconds while it runs.

**--dist** inlines the stylesheet, the application and the payload into a single file that
works from `file://` with no server. The SPA is not modified to do this: a small shim
installed ahead of `app.js` answers its four relative `fetch()` calls out of an embedded
map and stubs the WebSocket, so the same application code renders a frozen snapshot. That
keeps one implementation of every view instead of two.
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone

import dash_config
import payload as payload_mod

WEB = dash_config.WEB
DIST = dash_config.DIST

# Assets the single-file build folds in. `demo_data.js` is deliberately absent: it is the
# layout fixture and must never ship.
DIST_ASSETS = ("app.css", "app.js")


def emit_serve(payload: dict) -> None:
    out = WEB / "data.js"
    out.write_text("/* GENERATED by build_dashboard.py --serve - do not edit. */\n"
                   "window.DEMO = false;\nwindow.DASH = "
                   + json.dumps(payload, separators=(",", ":")) + ";\n",
                   encoding="utf-8")
    print(f"  wrote {out.relative_to(dash_config.REPO)} "
          f"({out.stat().st_size / 1e3:.0f} kB)")


def _embedded_files(payload: dict, with_curves: bool) -> dict[str, str]:
    """The relative URLs `app.js` fetches, mapped to their contents.

    Keys match exactly what the application asks for -- `paper_curves.json`, `live.json`
    and each `curves/<key>_<tf>.json` -- so the shim can answer without app.js knowing.
    A file that is simply absent (no desk has run yet, say) is left out, and the
    application's existing catch handles it the same way it would a 404.
    """
    files: dict[str, str] = {}
    names = ["live.json", "paper_curves.json"]
    if with_curves:
        names += [e["file"] for e in payload.get("curves", {}).values()]
    for name in names:
        p = WEB / name
        if p.exists():
            files[name] = p.read_text(encoding="utf-8")
    return files


SHIM = """
/* Single-file build. `app.js` is unmodified; these two stubs are what let it run with no
   server behind it. Every fetch it makes is same-origin and relative, so answering them
   from an embedded map is enough -- and anything not embedded falls through to a 404,
   which the application already treats as "no data" rather than an error. */
(function () {
  var FILES = window.__EMBEDDED__ || {};
  window.fetch = function (url) {
    var key = String(url).split("?")[0].replace(/^\\.\\//, "");
    if (Object.prototype.hasOwnProperty.call(FILES, key)) {
      return Promise.resolve({ ok: true, status: 200,
        json: function () { return Promise.resolve(JSON.parse(FILES[key])); },
        text: function () { return Promise.resolve(FILES[key]); } });
    }
    return Promise.resolve({ ok: false, status: 404, statusText: "not in this build",
      json: function () { return Promise.reject(new Error("404")); },
      text: function () { return Promise.resolve(""); } });
  };
  /* No socket to open from file://, and the real one would retry with backoff forever. */
  window.WebSocket = function () {
    return { close: function () {}, send: function () {}, readyState: 3 };
  };
})();
"""


def emit_dist(payload: dict, with_curves: bool) -> None:
    DIST.mkdir(parents=True, exist_ok=True)
    css = (WEB / "app.css").read_text(encoding="utf-8")
    app = (WEB / "app.js").read_text(encoding="utf-8")
    shell = (WEB / "index.html").read_text(encoding="utf-8")
    files = _embedded_files(payload, with_curves)

    # Take the body out of the served shell rather than restating the markup, so the two
    # builds cannot drift apart in structure the way the old pair did.
    body = shell[shell.index("<body>") + len("<body>"):shell.index("</body>")]
    body = body[:body.index("<script")]
    stamp = payload["generated_at"]

    doc = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>Stockhunt &middot; Truong's Dashboard</title>
<style>
{css}
</style>
</head>
<body>
{body}
<script>
window.DEMO = false;
window.DASH = {json.dumps(payload, separators=(",", ":"))};
window.__EMBEDDED__ = {json.dumps(files, separators=(",", ":"))};
window.__SNAPSHOT__ = true;
</script>
<script>{SHIM}</script>
<script>
  document.getElementById("m-feed").textContent = DASH.feed.source + " (snapshot)";
  document.getElementById("m-time").textContent = DASH.generated_at;
</script>
<script>
{app}
</script>
</body>
</html>
"""
    out = DIST / "dashboard.html"
    out.write_text(doc, encoding="utf-8")
    mb = out.stat().st_size / 1e6
    print(f"  wrote {out.relative_to(dash_config.REPO)} ({mb:.1f} MB, "
          f"{len(files)} embedded file(s), curves {'in' if with_curves else 'out'})")
    print(f"        snapshot of {stamp} - it cannot refresh itself")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--serve", action="store_true",
                    help="write web/data.js and web/curves/ for the served site")
    ap.add_argument("--dist", action="store_true",
                    help="write dist/dashboard.html, self-contained")
    ap.add_argument("--no-curves", action="store_true",
                    help="--dist only: leave the backtest curve JSONs out (~4 MB smaller; "
                         "rule detail pages then show no chart)")
    ap.add_argument("--offline", action="store_true",
                    help="skip the live price snapshot, the only network call here")
    args = ap.parse_args()

    if not (args.serve or args.dist):
        ap.error("nothing to do: pass --serve, --dist, or both")

    print(f"building dashboard payload  ({datetime.now(timezone.utc):%Y-%m-%d %H:%M UTC})")
    # --serve mirrors the curve files into web/; --dist alone must not touch the served
    # site, so it takes the index without the copies.
    data = payload_mod.build(copy_curve_files=args.serve, offline=args.offline)
    payload_mod.report(data)

    if args.serve:
        emit_serve(data)
    if args.dist:
        emit_dist(data, with_curves=not args.no_curves)


if __name__ == "__main__":
    main()
