"""Book-rule lists for the cells the leaderboard has never been scored on.

    python make_robustness_rules.py            # write lists + starts for the new cells
    python make_robustness_rules.py --list     # show what it would do, write nothing

**The population is the leaderboard itself, not the catalogue.** Scoring all ~1,180
candidates on twenty cells is a day and a half of compute to answer a question nobody
asked: most of them rank nowhere on any sheet. The rules already ON the board -- the
union of every sheet's shipped rows, 152 of them -- are the ones whose robustness is
worth measuring, and running only those turns the job from days into hours.

**The existing nine cells are NOT rewritten.** They already hold ~409 labels each, and
regenerating them from this 152-rule list would quietly shrink the live leaderboard by two
thirds. This writes lists only for cells that have no `book_<cls>_<tf>.csv` yet.

**What this buys, and what it does not.** `payload.robustness_index` reads `book_*.csv`
directly, so these runs populate the robustness matrix without `riskmatch_wf` -- which is
the expensive stage AND the one that rewrites `edge_standard.csv` whole. The cost is that
the new cells get no six-criteria verdict, so they will show a leaderboard of their own
only after a full riskmatch pass. That is the right trade for a robustness question:
"does this rule survive here" is a book measurement, "is it an edge" is a verdict.

**Read the result as an out-of-sample test of a SELECTED set.** These 152 were chosen as
the best of ~400 on the 1d/4h sheets. Their scores in a new cell are honest -- nothing
about `crypto 15m` was used to pick them -- but the selection still happened, so a rule
that looks good in ten cells is evidence and a rule that looks good in one is the
selection showing through. Deflation must use the ORIGINAL search size, not 152; see the
`--n-trials` / `--trial-dispersion` note in the root CLAUDE.md.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd

import wfo_paths  # noqa: F401  (path bootstrap)

sys.path.insert(0, str(Path(wfo_paths.__file__).resolve().parent))

import config  # noqa: F401,E402
import td_loader  # noqa: E402
from strategies.catalog import BASELINE, CONTROLS  # noqa: E402

from make_book_rules import oos_start  # noqa: E402

OUT = Path(__file__).resolve().parent / "book_rules"
UNION = OUT / "leaderboard_union.txt"
RESULTS = wfo_paths.RESULTS_DIR

CLASSES = ["us_stocks", "us_etfs", "crypto", "commodities", "cme_futures"]
TFS = ["1d", "4h", "1h", "15m"]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--list", action="store_true", help="report only, write nothing")
    a = ap.parse_args()

    if not UNION.exists():
        raise SystemExit(f"no {UNION} -- extract the leaderboard union first")
    union = [r.strip() for r in UNION.read_text(encoding="utf-8").splitlines()
             if r.strip() and not r.startswith("#")]
    head = [BASELINE] + list(CONTROLS)
    labels = head + [r for r in union if r not in head]
    print(f"{len(union)} leaderboard rules + {len(head)} baseline/controls "
          f"= {len(labels)} labels")

    rows, skipped = [], []
    for cls in CLASSES:
        for tf in TFS:
            book = RESULTS / f"book_{cls}_{tf}.csv"
            if book.exists():
                skipped.append(f"{cls} {tf} (already scored, {book.name})")
                continue
            try:
                data = td_loader.load(cls, tf)
            except Exception as exc:                       # noqa: BLE001
                skipped.append(f"{cls} {tf} (load failed: {str(exc)[:40]})")
                continue
            if len(data) < 3:
                skipped.append(f"{cls} {tf} (only {len(data)} symbols cached)")
                continue
            start, n_folds = oos_start(cls, tf)
            if start is None:
                skipped.append(f"{cls} {tf} (no folds)")
                continue
            rows.append({"class": cls, "tf": tf, "n_rules": len(labels),
                         "n_folds": n_folds,
                         "oos_start": pd.Timestamp(start).strftime("%Y-%m-%d")})
            if not a.list:
                (OUT / f"{cls}_{tf}.txt").write_text(
                    f"# {cls} {tf}: the {len(union)} rules on the leaderboard, baseline "
                    f"first.\n# Generated by make_robustness_rules.py -- do not "
                    f"hand-edit.\n" + "\n".join(labels) + "\n", encoding="utf-8")
            print(f"  {cls:12s} {tf:4s} {len(data):>3} symbols, {n_folds:>2} folds, "
                  f"oos from {rows[-1]['oos_start']}")

    for s in skipped:
        print(f"  skip {s}")

    if rows and not a.list:
        # Appended, never replaced: `run_book.sh` reads this file for its whole sheet
        # list, and the nine cells already scored still have to appear in it or a later
        # full run would silently drop them.
        starts = OUT / "starts.csv"
        new = pd.DataFrame(rows)
        if starts.exists():
            old = pd.read_csv(starts)
            keep = ~old.set_index(["class", "tf"]).index.isin(
                new.set_index(["class", "tf"]).index)
            new = pd.concat([old[keep], new], ignore_index=True)
        new.sort_values(["class", "tf"]).to_csv(starts, index=False)
        print(f"\nstarts.csv now lists {len(new)} cells")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
