"""Write one rule-list file per (class, tf) sheet, for `portfolio_wf --rules-file`.

The leaderboard is `results/edge_standard.csv`, so that is where the labels come from:
every rule the standard scored on a sheet gets a book row, and no rule that is not on the
leaderboard gets one. The baseline and the six signal-free controls are prepended because
a book sheet has to be able to answer "compared with what" from its own rows.

Also prints the `--start` each sheet needs. That date is fold 0's `is_end` from
`walkforward.generate_folds` over the class's union span -- the first bar that was ever
out-of-sample. The folds are 3y-IS / 1y-OOS / 1y-step and contiguous, so the union of
every fold's OOS window is one span from that date to the last bar, and a plain `--start`
reproduces it exactly but for the final bar (`fold_masks` uses `< oos_end`).

    python make_book_rules.py            # -> book_rules/<class>_<tf>.txt + starts.csv
"""
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
import wfo_paths  # noqa: F401,E402
import config  # noqa: F401,E402
import td_loader  # noqa: E402
import walkforward as wfmod  # noqa: E402
from config import MIN_BARS  # noqa: E402
from strategies.catalog import BASELINE, CONTROLS  # noqa: E402

OUT = Path(__file__).resolve().parent / "book_rules"


def oos_start(asset_class: str, timeframe: str):
    """Fold 0's `is_end`: the first bar of the walk-forward out-of-sample union."""
    data = td_loader.load(asset_class, timeframe)
    data = {s: df for s, df in data.items() if len(df) >= MIN_BARS}
    if not data:
        return None, 0
    start = min(df.index[0] for df in data.values())
    end = max(df.index[-1] for df in data.values())
    folds = wfmod.generate_folds(start, end)
    return (folds[0].is_end if folds else None), len(folds)


def main() -> None:
    OUT.mkdir(exist_ok=True)
    edge = pd.read_csv(wfo_paths.RESULTS_DIR / "edge_standard.csv")
    head = [BASELINE] + list(CONTROLS)
    rows = []
    for (cls, tf), g in edge.groupby(["class", "tf"]):
        labels = head + [r for r in sorted(g["rule"].unique()) if r not in head]
        path = OUT / f"{cls}_{tf}.txt"
        path.write_text(
            f"# {cls} {tf}: every rule on results/edge_standard.csv, baseline first.\n"
            f"# Generated by make_book_rules.py -- do not hand-edit.\n"
            + "\n".join(labels) + "\n", encoding="utf-8")
        start, n_folds = oos_start(cls, tf)
        rows.append({"class": cls, "tf": tf, "n_rules": len(labels),
                     "n_folds": n_folds,
                     "oos_start": start.date() if start is not None else ""})
        print(f"{cls:12}{tf:4} {len(labels):4} rules -> {path.name}"
              f"   --start {start.date() if start is not None else '?'}"
              f"  ({n_folds} folds)")

    df = pd.DataFrame(rows)
    df.to_csv(OUT / "starts.csv", index=False)
    print(f"\nwrote {OUT / 'starts.csv'}")


if __name__ == "__main__":
    main()
