#!/usr/bin/env bash
# The verdict, then the book rule lists, then the books, then the store, then the
# pessimistic fill. One script, because chaining it through waiter scripts is how the
# 2026-08-26 run lost seven hours.
#
# THE WAITER THAT DEADLOCKED, RECORDED SO IT IS NOT WRITTEN AGAIN. The first version of
# this waited for strat_wf two ways -- a log marker, then `ps -ef | grep -c '[s]trat_wf'`
# reaching zero. The second condition can never be true, because THIS SCRIPT'S OWN
# COMMAND LINE CONTAINS THE PATTERN: `ps` lists the bash process running it, the grep
# matches its text, and the count floors at one. `strat_wf` had exited cleanly at 10:03
# and the pipeline sat on that loop until somebody looked. The bracket trick only stops
# grep matching ITSELF; it does nothing about a caller that quotes the same string.
#
# A stage's own exit code is the signal. Do not poll the process table for it.
#
# AND DO NOT EDIT THIS FILE WHILE IT IS RUNNING. bash reads a script by BYTE OFFSET, so
# rewriting it mid-run shifts every line after the cursor: the 2026-08-26 run executed
# every stage correctly and then died on a syntax error at the closing echo, which meant
# the completion marker never printed and a downstream waiter held forever. Copy it, edit
# the copy.
set -u
cd "$(dirname "$0")"
# ABSOLUTE. A relative interpreter path breaks the moment a step runs inside a
# subshell that has cd'd somewhere else -- `(cd .. && "$PY" ...)` resolved
# ../.venv from the REPO ROOT, i.e. outside the repo, and the ingest step failed
# in under a second while the log said DONE.
PY="$(cd .. && pwd)/.venv/Scripts/python"
./run_promote_riskmatch.sh
echo "=== merge $(date -u +%H:%M:%S) ==="
"$PY" -u merge_edge_standard.py
echo "=== book rule lists $(date -u +%H:%M:%S) ==="
"$PY" -u make_book_rules.py
./run_promote_books.sh
echo "=== ingest $(date -u +%H:%M:%S) ==="
(cd .. && "$PY" -u tools/ingest_results.py)
echo "=== INGEST DONE $(date -u +%H:%M:%S) ==="
./run_promote_open.sh
echo "=== CHAIN DONE $(date -u +%H:%M:%S) ==="
