#!/usr/bin/env bash
# The 1m/2m/3m Heikin-Ashi study: 8 Pine conversions at CHART lengths, on plain and
# on synthetic candles, per class and timeframe. Pre-registered 2026-08-20 in
# data/reference/trials.csv (384 cells).
#
# BASH, nohup, `python -u`, per the repo's launch rule -- the PowerShell form turns
# numpy's RuntimeWarnings into terminating errors and dies silently two minutes in.
#
# DO NOT EDIT THIS FILE WHILE IT IS RUNNING. Bash reads a script by byte offset as it
# executes, so an edit shifts everything it has not yet reached and the rest of the run
# is undefined. Kill it, edit, relaunch -- `run_sheet` skips finished sheets, so a
# relaunch costs only the sheet that was in flight.
#
# Ordered so partial results are useful if this is interrupted: `us_stocks` first
# because its 1m cache is already complete, coarse timeframes before fine, and
# `lorentzian_knn` -- which walks bar by bar and is ~100x the cost of everything else --
# in its own pass at the end. The other three classes WAIT on the 1m fetch that is
# filling their cache, then resample themselves; a sheet is never scored on a universe
# that is still half-downloaded.

set -x
PY=../.venv/Scripts/python
ENGINE="../backtest engine"
FETCH_LOG="$ENGINE/logs/fetch_1m_batch.log"
mkdir -p logs results

FAST="bar_updn pivot_center range_filter range_filter_macd ema_cross_sniper bb_outside_in ssl_hybrid"
SLOW="lorentzian_knn"
CONTROLS="BUYHOLD RANDOM_50 RANDOM_75"

# Every base label gets both wraps: `chart:` is Pine bar-count semantics on real
# candles, `ha:chart:` the same signal computed on Heikin-Ashi candles. The pair IS the
# experiment -- a number from the second means nothing without the first beside it.
expand () {
    for r in $1; do
        for w in "chart:" "ha:chart:"; do
            printf '%s%s %s%s@allow_short=0 ' "$w" "$r" "$w" "$r"
        done
    done
}

# run_sheet <class> <tf> <rules> <tag> [extra portfolio_wf flags...]
# The `shift 4` is load-bearing: without it the extra flags land in $5 and are silently
# DROPPED, and phase 3 would write a byte-identical copy of phase 1 under a name saying
# it was flattened.
run_sheet () {
    local cls=$1 tf=$2 rules=$3 tag=$4
    shift 4
    local out="convert_ha_${cls}_${tf}${tag}.csv"
    # Resumable: a finished sheet is skipped, so a relaunch costs only what was in
    # flight rather than re-scoring hours of completed work.
    if [ -s "results/$out" ]; then
        echo "=== skip ${cls}/${tf}${tag} (already written) ==="
        return 0
    fi
    $PY -u portfolio_wf.py --class "$cls" --tf "$tf" \
        --rules $(expand "$rules") $CONTROLS "$@" \
        --out "$out" \
        > "logs/convert_ha_${cls}_${tf}${tag}.log" 2>&1
    echo "=== done ${cls}/${tf}${tag} rc=$? ==="
}

# ---------------------------------------------------------- phase 1: us_stocks
( cd "$ENGINE" && $PY -u resample_intraday.py --class us_stocks --tf 2m 3m )
for tf in 3m 2m 1m; do run_sheet us_stocks "$tf" "$FAST" ""; done

# ------------------------------------------- phase 2: the classes still fetching
while ! grep -q "FETCH BATCH DONE" "$FETCH_LOG" 2>/dev/null; do
    echo "waiting on 1m fetch: $(date +%H:%M:%S)"
    sleep 300
done
( cd "$ENGINE" && $PY -u check_data.py --fix )
( cd "$ENGINE" && $PY -u resample_intraday.py --class crypto us_etfs commodities --tf 2m 3m )
for tf in 3m 2m 1m; do
    for cls in crypto us_etfs commodities; do run_sheet "$cls" "$tf" "$FAST" ""; done
done

# ---------------------------------------------- phase 3: the end-of-day BOUND
# The same cells with every non-baseline rule forced flat into each session's close.
# Neither convention is free, which is why both are reported rather than one chosen:
# unflattened lets a "day-trading" rule collect the overnight drift that is 65-95% of US
# equity return, while flattened charges a handicap the Pine author never took -- a
# no-signal always-long book scores IR -0.59 to -0.84 on flattening alone. Same shape as
# `--fill`: a bound, not a correction. Crypto is skipped; it has no session to flatten.
for tf in 3m 2m 1m; do
    for cls in us_stocks us_etfs commodities; do
        run_sheet "$cls" "$tf" "$FAST" "_flat" --flatten-eod
    done
done

# ------------------------------------------------------- phase 4: the slow one
for tf in 3m 2m 1m; do
    for cls in us_stocks crypto us_etfs commodities; do
        run_sheet "$cls" "$tf" "$SLOW" "_knn"
    done
done

echo "INTRADAY HA STUDY COMPLETE"
